### ISSUE TITLE
Excpetion in sender 

### ISSUE THREAD

**Issue by robob80** [logzio/logzio-java-sender#26]
After last version upgrade (1.0.14) I receive NullPointerException in LogzioSender.
Due to this bug downgraded to version 1.0.11

**Comment by robob80** [comment]
Hi , all I have is this image which i took yesterday.
I f i am not mistaked it is has an url with null value (I think it sooposed
to be logz.io url )
I will try to reproduce it from memory
public void somefunction(String url){
if (url.equals(somthing)){   -> Exception is thrown here (url = null)
  dosomething ....
}


Hope this helps

**Comment by idohalevi** [comment]
@robob80 
Do you remember how did you build the sender?

**Comment by robob80** [comment]
public LogzService(String path , String name , boolean console) throws
LogzioParameterErrorException {
this.console = console;
this.source = name;
index =0;
sender = LogzioSender.getOrCreateSenderByType(token, name, 5,98, new
File(path),
null, 10 * 1000, 10 * 1000, true,
new LogzioStatusReporter(false), Executors.newScheduledThreadPool(2),30);
sender.start();
}

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality6&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality6&>
23.08.18,
15:45:54

**Comment by idohalevi** [comment]
@robob80 
Thank you.  I will add a null check to the builder. But if it will still not work if you won't give the constructor URL that is not null or LogzioStatusReporter

**Comment by robob80** [comment]
Can you send an example of what do you mean , I have implemented this based
on some example in your documentation - I don't remeber what each of them
is doing  but i know what thing it is worknig in version 11

**Comment by robob80** [comment]
O.K I am passing already my token , do you need my url also ? as i said i
made this based on some example , In any case maybe you should add
parameter exception to notify users when bad input is entered,
belive it took  a quite a while to understand why it stoped working
yesterday (I have deployed the system and for some reason it didn't work)

**Comment by idohalevi** [comment]
@robob80  
I will add a check, any idea where you found this example so I could fix it too?

**Comment by robob80** [comment]
I have to say that i don't remember but i will try to look it up.
Actually as I see now maybe the example wasn't the best
You see currently I am sending following command
sender = LogzioSender.getOrCreateSenderByType(token, name, 5,98, new
File(path), null, 10 * 1000, 10 * 1000, true, new
LogzioStatusReporter(false), Executors.newScheduledThreadPool(2),30);

but if the name parameter contains white space the log is not sent - Is
this in purpose ?
and if so which parameter should be sent there ?

**Comment by idohalevi** [comment]
@robob80 again, it looks like you are missing the URL, please go to the log shipping page in the app, select one of the java senders (log4j or log appender), and check what is your url
