### ISSUE TITLE
ability to add custom headers

### ISSUE THREAD

**Issue by niteshsinha** [logzio/logzio-java-sender#48]
Hi, 

Is there an ability yet, or a feature request planned to add custom headers to the configuration before sending http request?

for eg: adding a user defined RequestProperty to `HttpURLConnection` ?

**Comment by idohalevi** [comment]
@niteshsinha 
Currently, we do not have this feature planned. Can you describe the use-case for which it will help you?

**Comment by idohalevi** [comment]
Yes, this is dedicated to Logz.io. You can always fork this repo and make the necessary changes for your needs
